name: Lint & Format
on: [push, pull_request]
jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install flake8 black isort
      - name: Run linters
        run: |
          source .venv/bin/activate
          flake8 axel tests
          isort --check-only axel tests
          black --check axel tests
