name: Lint & Format
on: [push, pull_request]
jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install pre-commit
      - name: Run pre-commit
        run: |
          source .venv/bin/activate
          pre-commit run --all-files --show-diff-on-failure
